version: 2

models:
  - name: fact_page_views
    description: Contains all page view events from greenery
    columns: 
      - name: user_guid
        description: unique user that this event is associated with
        tests:
          - unique
          - not_null
      - name: page_view_id
        description: unique event on the platform
        tests:
          - unique
          - not_null
      - name: event_type
        description: type of event (add_to_cart, checkout, page_view, package_shipped) in order workflow
        tests:
          - unique
          - not_null	 
      - name: page_url
        description: URL that the event happened on
        tests:
          - unique
          - not_null
      - name: session_guid
        description: unique ID of each browsing session on the platform which can contain many events
        tests:
          - unique
          - not_null       
      - name: events_created_at_utc    
        description: timestamp of the event
        tests:
          - unique
          - not_null
      - name: insertion_timestamp_pfpv
        description: table insertion timestamp       	            		

  - name: fact_user_session_product
    description: contains all pageview events from greenery
    columns: 
      - name: product_guid 
        description: unique UUID of each product 
        tests:
          - unique
          - not_null
      - name: product_name
        description: name of product
        tests:
          - unique
          - not_null
      - name: conver_rate_by_prod
        description: summation of addtocart events / unique count of event sessions
        tests:
          - unique
          - not_null
      - name: insertion_timestamp_pfusp
        description: table insertion timestamp

  - name: prodcut_funnel
    description: contains product event total sessions and session flow/conversion rate
    columns: 
      - name: total_sessions
        description: total_sessions of the different web session events
        tests:
          - unique
          - not_null
      - name:  page_views
        description: unique not nulll page_views event type
        tests:
          - unique
          - not_null
      - name: add_to_carts
        description: unique not nulll add_to cart event type
        tests:
          - unique
          - not_null
      - name: checkouts
        description: unique not nulll checkout event type
        tests:
          - unique
          - not_null                    
      - name: page_view_flow
        description: landing to product page view conversion
        tests:
          - unique
          - not_null
      - name:  view_cart_flow 
        description: from page_view to add_to_cart flow conversion rate
        tests:
          - unique
          - not_null
      - name: cart_checkout_flow
        description: from add_to_cart to checkout flow conversion rate
        tests:
          - unique
          - not_null
      - name: page_view_checkout_flow
        description: from landing - product page views to checkout conversion rate
        tests:
          - unique
          - not_null               	            		

  - name: fact_product_orders_pivoted
    description: aggregated order information
    columns:
      - name: product_guid
        description: unique UUID of each product 
        tests:
        - not_null
        - unique
      - name: product_name
        description: name of product
        tests:
        - not_null
        - unique 
      - name: units sold
        tests:
        - not_null
        - unique         
      - name: expected_rev_no_disc_tax
        tests:
        - not_null
        - unique         
      - name: current_inventory
        tests:
        - not_null
        - unique 
      - name: adjusted_inventory
        tests:
        - not_null
        - unique         
      - name: num_times_ordered
        tests:
        - not_null
        - unique  
      - name: num_users_ordered
        tests:
        - not_null
        - unique  
      - name: last_ordered  
        tests:
        - not_null
        - unique  
